Repository Leap-MERN-2023/nomad-tour, pull requests merged in 2024-03, with the labels that each got.

#15 Flight controller All CRUD with model
  server/src/controller/airportController.ts
  server/src/controller/flightController.ts
  server/src/index.ts
  server/src/model/airport.ts
  server/src/model/flight.ts
  server/src/routes/airportRoutes.ts
  server/src/routes/flightRoutes.ts
  server/tsconfig.json
Labels: enhancement

#16 country controller All CRUD
  server/src/controller/country.ts
  server/src/index.ts
  server/src/model/country.ts
  server/src/routes/country.ts
Labels: documentation

#23 fix conflict
  server/src/controller/airportController.ts
  server/src/model/airport.ts
  server/src/routes/airportRoutes.ts
Labels: documentation

#27 12 auth controller create get
  server/src/controller/authController.ts
  server/src/routes/authRoutes.ts
Labels: documentation

#28 hotel card hiiw
  client/package-lock.json
  client/package.json
  client/public/Star.png
  client/public/location.png
  client/src/components/hotelcard/index.tsx
  client/src/components/hotelcard/slider/index.tsx
  client/tailwind.config.ts
Labels: documentation

#32 Hero section
  client/package.json
  client/src/components/heroSection/HeroSection.tsx
  client/src/components/heroSection/MySelect.tsx
  client/src/components/heroSection/Tabs.tsx
  client/src/components/heroSection/navbar.tsx
Labels: help wanted

#22 cloudinary install, uplouded image and checked postman
  server/package-lock.json
  server/package.json
  server/src/controller/airportController.ts
  server/src/controller/country.ts
  server/src/controller/upload.ts
  server/src/index.ts
  server/src/middleware/multer.ts
  server/src/model/country.ts
  server/src/model/hotel.ts
  server/src/routes/country.ts
  server/src/routes/upload.ts
  server/src/utils/cloudinary.ts
  server/src/utils/multer.ts
  server/upload/0e5058a38d2a957407dfa4252d6aa884
  server/upload/1d10a98e462774cf0f5bb7ad9931720a
  server/upload/237dfc16e360078e1d441e7e37301ddc
  server/upload/34df64fcd7c113c32b533a3d52a2679d
  server/upload/37b85af9f33645dff3d74e2de4e4414a
  server/upload/45f2b2cb7b00273d7861cf13007c94c7
  server/upload/734c1028e7dc78329e252ac1396ffc46
  server/upload/9395905a1fb539e41011637218811a5d
Labels: documentation, good first issue

#37 airport context hiiw
  client/package-lock.json
  client/package.json
  client/src/app/layout.tsx
  client/src/context/airportProvider.tsx
  server/src/index.ts
Labels: documentation

#39 Hero section almost done
  client/src/components/heroSection/Banner.tsx
  client/src/components/heroSection/Carousel.tsx
  client/src/components/heroSection/HeroSection.tsx
  client/src/components/heroSection/Tabs.tsx
  client/src/components/heroSection/navbar.tsx
  client/src/constants/index.ts
Labels: good first issue

#41 Country context
  client/package-lock.json
  client/package.json
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/src/components/country/additionImage.tsx
  client/src/components/country/explore.tsx
  client/src/components/country/index.tsx
  client/src/components/hotelcard/index.tsx
  client/src/components/index.tsx
  client/src/context/CountryProvider.tsx
  client/src/context/airportProvider.tsx
Labels: documentation

#44 42 hotel context fix country carousels
  client/src/app/layout.tsx
  client/src/components/country/explore.tsx
  client/src/components/country/index.tsx
  client/src/context/CountryProvider.tsx
  client/src/context/hotelProvider.tsx
  server/src/controller/hotel.ts
  server/src/routes/hotel.ts
Labels: bug, documentation

#48 email section hiilee
  client/src/app/page.tsx
  client/src/components/emailSection/index.tsx
  server/src/index.ts
Labels: documentation

#54 Footer with responsive
  client/package-lock.json
  client/public/visaCard.png
  client/src/app/page.tsx
  client/src/components/Footer/index.tsx
  client/src/components/testSection/slider/index.tsx
Labels: help wanted

#55 46 search page
  client/src/app/(pages)/searchFlight/page.tsx
  client/src/app/layout.tsx
  client/src/components/country/explore.tsx
  client/src/components/country/index.tsx
  client/src/components/flightSearch/FlightInfo.tsx
  client/src/components/heroSection/Carousel.tsx
  client/src/components/heroSection/FlightSearch.tsx
  client/src/components/heroSection/HeroSection.tsx
  client/src/components/heroSection/MySelect.tsx
  client/src/components/heroSection/Tabs.tsx
  client/src/components/heroSection/navbar.tsx
  client/src/components/hotelcard/slider/index.tsx
  client/src/constants/index.ts
  client/src/context/CountryProvider.tsx
  client/src/context/flightProvider.tsx
  client/src/context/hotelProvider.tsx
  client/src/types/index.ts
  package-lock.json
  server/src/controller/airportController.ts
  server/src/controller/flightController.ts
  server/src/controller/hotel.ts
  server/src/model/airport.ts
Labels: enhancement

#56 cartuud responsive hiiw
  client/src/components/newsCard/index.tsx
  client/src/components/newsCard/slider/index.tsx
  client/src/components/newsSection/index.tsx
  client/src/components/newsSection/slider/index.tsx
  client/src/components/testSection/index.tsx
  client/src/components/testSection/slider/index.tsx
  client/src/components/testimonialCard/index.tsx
Labels: bug

#57 51 sign up modal
  client/src/app/layout.tsx
  client/src/components/LoginForm/index.tsx
  client/src/components/emailSection/index.tsx
  client/src/components/heroSection/navbar.tsx
  client/src/context/UserProvider/index.tsx
  server/src/controller/authController.ts
Labels: documentation
