Repository Leap-MERN-2023/nomad-tour, pull requests merged in 2024-04, with the labels that each got.

#62 60 little style fix hoc fix
  client/src/app/(pages)/searchFlight/page.tsx
  client/src/app/globals.css
  client/src/app/page.tsx
  client/src/components/country/explore.tsx
  client/src/components/country/index.tsx
  client/src/components/emailSection/index.tsx
  client/src/components/flightSearch/FlightFilter.tsx
  client/src/components/flightSearch/FlightInfo.tsx
  client/src/components/heroSection/Banner.tsx
  client/src/components/heroSection/HeroSection.tsx
  client/src/components/heroSection/navbar.tsx
  client/src/components/hotelSection/index.tsx
  client/src/components/newsCard/index.tsx
  client/src/components/newsSection/index.tsx
  client/src/components/testSection/index.tsx
  client/src/constants/index.ts
  client/src/hoc/SectionCenterer.tsx
Labels: enhancement

#65 context bolon model bichiw
  admin/jsconfig.json
  admin/package-lock.json
  admin/package.json
  admin/public/assets/nomad.png
  admin/src/app/admin/airport/page.jsx
  admin/src/app/admin/all-trips/page.js
  admin/src/app/admin/attractions/page.js
  admin/src/app/admin/country/page.jsx
  admin/src/app/admin/flight/page.jsx
  admin/src/app/admin/hotel/page.jsx
  admin/src/app/admin/layout.js
  admin/src/app/admin/page.js
  admin/src/app/admin/rooms/page.js
  admin/src/app/admin/transport/page.js
  admin/src/app/admin/travels/page.js
  admin/src/app/admin/user/page.jsx
  admin/src/app/globals.css
  admin/src/app/layout.js
  admin/src/app/layout.jsx
  admin/src/app/page.jsx
  admin/src/components/modals/airportModal/index.tsx
  admin/src/components/modals/countryModal/index.tsx
  admin/src/components/modals/flightModal/index.tsx
  admin/src/components/modals/hotelModal/index.tsx
  admin/src/components/sections/airportViem/index.tsx
  admin/src/components/sections/countryViem/index.tsx
  admin/src/components/sections/flightViem/index.tsx
  admin/src/components/sections/hotelViem/hotelcard/index.tsx
  admin/src/components/sections/hotelViem/hotelcard/slider/index.tsx
  admin/src/components/sections/hotelViem/index.tsx
  admin/src/components/sections/usersViem/index.tsx
  admin/src/components/tripit/calendar/calendar.js
  admin/src/components/tripit/chart/chart.js
  admin/src/components/tripit/destination-card/destination-card.js
  admin/src/components/tripit/featured/featured.js
  admin/src/components/tripit/header/header-account.js
  admin/src/components/tripit/header/header-search-bar.js
  admin/src/components/tripit/map/map.js
  admin/src/components/tripit/people-card/people-card.js
  admin/src/components/tripit/sidebar/sidebar.js
  admin/src/components/tripit/timeline/timeline.js
  admin/src/components/tripit/todos/todos.js
  admin/src/components/tripit/travel-date-card/travel-date-card.js
  admin/src/components/tripit/ui/button.jsx
  admin/src/components/tripit/weather/weather.js
  admin/src/context/airportProvider.tsx
  admin/src/context/authProvider.tsx
  admin/src/context/countryProvider.tsx
  admin/src/context/flightProvider.tsx
  admin/src/context/hotelProvider.tsx
  admin/src/lib/constants.js
  admin/src/styles/globals.css
  admin/tailwind.config.js
  admin/tsconfig.json
  server/src/controller/airportController.ts
Labels: documentation

#68 63 tickets
  client/package-lock.json
  client/package.json
  client/src/app/layout.tsx
  client/src/components/flightSearch/FlightInfo.tsx
  client/src/context/ticketProvider.tsx
  client/src/utils/dateFormat.ts
  client/src/utils/priceCalc.ts
  node_modules/.package-lock.json
  server/src/controller/airlineController.ts
  server/src/controller/flightController.ts
  server/src/controller/ticketController.ts
  server/src/index.ts
  server/src/model/airline.ts
  server/src/model/flight.ts
  server/src/model/tickets.ts
  server/src/routes/airlineRoutes.ts
  server/src/routes/ticketsRoutes.ts
Labels: enhancement

#73 hotel tab
  client/src/app/layout.tsx
  client/src/components/Footer/index.tsx
  client/src/components/heroSection/Tabs.tsx
  client/src/components/hotelSection/index.tsx
  client/src/context/CountryProvider.tsx
  client/src/context/ticketProvider.tsx
  node_modules/.package-lock.json
Labels: duplicate

#81 admin page duusaw
  admin/public/assets/location.jpg
  admin/public/assets/star.png
  admin/src/components/modals/flightModal/index.tsx
  admin/src/components/modals/ticketModal/index.tsx
  admin/src/components/sections/airlinesViem/index.tsx
  admin/src/components/sections/airportViem/index.tsx
  admin/src/components/sections/countryViem/index.tsx
  admin/src/components/sections/flightViem/index.tsx
  admin/src/components/sections/hotelViem/hotelcard/index.tsx
  admin/src/components/sections/hotelViem/hotelcard/slider/index.tsx
  admin/src/components/sections/hotelViem/index.tsx
  admin/src/components/sections/ticketViem/index.tsx
  admin/src/components/sections/usersViem/index.tsx
  admin/src/components/tripit/people-card/people-card.js
  admin/src/components/tripit/sidebar/sidebar.js
  admin/src/components/tripit/weather/weather.js
  admin/src/context/airlines.tsx
  admin/src/context/airportProvider.tsx
  admin/src/context/authProvider.tsx
  admin/src/context/countryProvider.tsx
  admin/src/context/flightProvider.tsx
  admin/src/context/hotelProvider.tsx
  admin/src/context/ticket.tsx
Labels: documentation

#87 fix
  admin/src/app/page.jsx
  admin/src/components/sections/hotelViem/hotelcard/index.tsx
  admin/src/components/sections/hotelViem/hotelcard/slider/index.tsx
Labels: documentation

#93 Hotel search
  admin/src/components/sections/airlinesViem/index.tsx
  client/.env
  client/package-lock.json
  client/package.json
  client/src/app/(pages)/hotels/rooms/order/page.tsx
  client/src/app/(pages)/hotels/rooms/page.tsx
  client/src/app/layout.tsx
  client/src/components/GoogleMaps/index.tsx
  client/src/components/Order/index.tsx
  client/src/components/heroSection/Tabs.tsx
  client/src/components/hotelcard/HotelModal.tsx
  client/src/components/hotelcard/SerchHotelCard.tsx
  client/src/components/hotelcard/index.tsx
  client/src/components/pages/Hotel/drawer.tsx
  client/src/components/pages/Hotel/drawerData.tsx
  client/src/components/pages/Hotel/index.tsx
  client/src/components/pages/Rooms/carousel.tsx
  client/src/components/pages/Rooms/index.tsx
  client/src/components/pages/Rooms/roomInfo.tsx
  client/src/context/RoomProvider.tsx
  client/src/context/hotelProvider.tsx
  client/src/types/index.ts
  server/src/controller/hotel.ts
  server/src/controller/orderRoom.ts
  server/src/controller/room.ts
  server/src/index.ts
  server/src/model/hotel.ts
  server/src/model/order/order.ts
  server/src/model/rooms.ts
  server/src/routes/hotel.ts
  server/src/routes/order.ts
  server/src/routes/room.ts
Labels: documentation

#99 fix admin
  admin/package-lock.json
  admin/package.json
  admin/public/assets/campfire.jpg
  admin/public/assets/nomad.png
  admin/public/assets/star.png
  admin/src/app/admin/page.js
  admin/src/app/layout.jsx
  admin/src/app/page.jsx
  admin/src/components/modals/airportModal/index.tsx
  admin/src/components/modals/flightModal/index.tsx
  admin/src/components/modals/hotelModal/index.tsx
  admin/src/components/sections/HomeViem/index.tsx
  admin/src/components/sections/airlinesViem/airlineCard/index.tsx
  admin/src/components/sections/airlinesViem/index.tsx
  admin/src/components/sections/airportViem/airportCard/index.tsx
  admin/src/components/sections/airportViem/index.tsx
  admin/src/components/sections/flightViem/flightCard/index.tsx
  admin/src/components/sections/flightViem/index.tsx
  admin/src/components/sections/hotelViem/hotelcard/index.tsx
  admin/src/components/sections/hotelViem/index.tsx
  admin/src/components/sections/usersViem/index.tsx
  admin/src/components/sections/usersViem/userCard/index.tsx
  admin/src/components/tripit/header/header-account.js
  admin/src/components/tripit/sidebar/sidebar.js
  admin/src/context/airlines.tsx
  admin/src/context/airportProvider.tsx
  admin/src/context/authProvider.tsx
  admin/src/context/countryProvider.tsx
  admin/src/context/flightProvider.tsx
  admin/src/context/hotelProvider.tsx
  admin/src/context/ticket.tsx
  admin/src/lib/constants.js
  server/src/controller/airlineController.ts
  server/src/controller/airportController.ts
  server/src/controller/flightController.ts
  server/src/controller/hotel.ts
  server/src/index.ts
  server/src/routes/airlineRoutes.ts
Labels: documentation

#102 Hotel search
  client/src/app/(pages)/hotels/rooms/order/page.tsx
  client/src/app/(pages)/hotels/rooms/order/pay/page.tsx
  client/src/components/GoogleMaps/index.tsx
  client/src/components/Order/index.tsx
  client/src/components/hotelcard/HotelModal.tsx
  client/src/components/hotelcard/SerchHotelCard.tsx
  client/src/components/hotelcard/index.tsx
  client/src/components/pages/PayRoom/OrderInfo.tsx
  client/src/components/pages/PayRoom/PayPath.tsx
  client/src/components/pages/Rooms/index.tsx
  client/src/context/RoomProvider.tsx
  client/src/context/UserProvider/index.tsx
  server/src/controller/flightController.ts
  server/src/controller/orderRoom.ts
  server/src/controller/room.ts
  server/src/routes/room.ts
Labels: documentation

#104 fix admin last
  admin/public/assets/correct.jpg
  admin/src/components/modals/airlineModal/index.tsx
  admin/src/components/modals/hotelModal/index.tsx
  admin/src/components/sections/HomeViem/index.tsx
  admin/src/components/sections/airlinesViem/airlineCard/index.tsx
  admin/src/components/sections/airportViem/airportCard/index.tsx
  admin/src/components/sections/flightViem/flightCard/index.tsx
  admin/src/components/sections/hotelViem/hotelcard/index.tsx
  admin/src/components/sections/usersViem/userCard/index.tsx
  admin/src/components/tripit/header/header-account.js
  admin/src/context/airlines.tsx
  admin/src/context/airportProvider.tsx
  admin/src/context/authProvider.tsx
  admin/src/context/flightProvider.tsx
  admin/src/context/hotelProvider.tsx
  client/src/components/LoginForm/index.tsx
Labels: documentation
